version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    networks:
      - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/data'
    env_file: 
      - ./envs/mysql/common.env  

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.4-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
      - './zabbix/externalscripts:/usr/lib/zabbix/externalscripts'    
    env_file: 
      - ./envs/zabbix-server/common.env  
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.4-latest
    networks:
      - network-zabbix
    links:
      - mysql
    restart: always
    ports:
      - '80:8080'
      - '443:8443'
    env_file: 
      - ./envs/zabbix-frontend/common.env    
    depends_on:
      - mysql
   
  grafana:
    container_name: grafana 
    image: grafana/grafana:8.2.7
    networks:
      - network-zabbix
    links:
      - mysql
      - zabbix-server
    restart: always
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app 
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - zabbix-server
  
