version: "3.7"

x-deploy: &template-deploy
#replicas: 1 
  restart_policy:
    condition: on-failure
  update_config:
    parallelism: 1
    delay: 10s

services:
  mysql:
    image: mysql:5.7
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    networks:
     - network-zabbix
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment:
      - MYSQL_ROOT_PASSWORD={DEFINA A SENHA DE ADMINISTRADOR DO MYSQL}
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER={DEFINA O USUÁRIO DO MYSQL}
      - MYSQL_PASSWORD={DEFINA A SENHA DE ADMINISTRADOR DO MYSQL}
    deploy: 
      <<: *template-deploy  

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-5.4-latest
    networks:
     - network-zabbix
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
      - './zabbix/externalscripts:/usr/lib/zabbix/externalscripts'    
    env_file: 
      - ./envs/zabbix-server/common.env  
    depends_on:
      - mysql

  zabbix-frontend:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.4-latest
    networks:
    - network-zabbix
    ports:
      - '80:8080'
      - '443:8443'
    env_file: 
      - ./envs/zabbix-frontend/common.env  
    deploy: 
       <<: *template-deploy  	
    depends_on:
      - mysql
   
  grafana:
    image: grafana/grafana:8.2.7
    networks:
    - network-zabbix
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app 
    ports:
      - '3000:3000'
    deploy: 
      <<: *template-deploy  	  
    depends_on:
      - mysql
      - zabbix-server
        
networks: 
  network-zabbix:
